name: Deploy Django Image to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'image.tf'  # image.tf 파일의 변경 사항만 감지

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      ECR_REPOSITORY_DJANGO: "891377402975.dkr.ecr.ap-northeast-2.amazonaws.com/django-app-repo"
      ECS_CLUSTER: "main-cluster"
      ECS_SERVICE: "app-service"
      ECS_TASK_DEFINITION: "app-task"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REPOSITORY_DJANGO }}

    - name: Pull, tag and push Django Docker image to ECR
      id: pull-and-push-django
      run: |
        docker pull wangamy/newticket:latest
        docker tag wangamy/newticket:latest ${{ env.ECR_REPOSITORY_DJANGO }}:latest
        docker push ${{ env.ECR_REPOSITORY_DJANGO }}:latest

    - name: Run Terraform to update ECS service
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        terraform init -backend-config="path=terraform.tfstate"  # 기존 상태 파일과 일치시키기 위해 backend 경로를 지정
        terraform apply -auto-approve -target=null_resource.push_django_image -target=null_resource.force_ecs_deployment
